packages:
  - core
  - gitlab
  - github
  - service
  - web

allowBuilds:
  '@google/genai': false
  '@nkzw/mdx-editor': true
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  native-keymap: true
  node-pty: true
  protobufjs: false
  sharp: true
  workerd: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@nkzw/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.0
  vite-plus: ^0.3.0
  vitest: 4.1.11
nodeLinker: hoisted
onlyBuiltDependencies:
  - '@nkzw/mdx-editor'
  - '@swc/core'
  - electron
  - electron-winstaller
  - unrs-resolver
overrides:
  extract-zip>yauzl: ^3.4.0
  vite: 'catalog:'
  vitest: 'catalog:'
patchedDependencies:
  native-keymap@3.3.9: patches/native-keymap@3.3.9.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
