export {
  attachVersionCommentReferences,
  buildWalkthroughPrompt,
  buildWalkthroughPromptInput,
  combineCommitWalkthroughs,
  composeUnitWalkthroughs,
  indexWalkthroughHunks,
  maxHunksPerGroup,
  maxLargePatchExcerpt,
  maxLargeTotalPatchExcerpt,
  maxPatchExcerpt,
  maxProseChars,
  maxTotalPatchExcerpt,
  maxWalkthroughChapters,
  maxWalkthroughStops,
  normalizeAuthoredWalkthrough,
  normalizeWalkthroughDraft,
  parseAuthoredWalkthrough,
  parseRepositoryState,
  parseWalkthroughDraft,
  repositoryStateSchema,
  walkthroughDraftAgentOutputSchema,
  walkthroughDraftSchema,
  type AuthoredWalkthrough,
  type UnitWalkthroughEntry,
  type WalkthroughDraft,
  type WalkthroughPromptOptions,
  type WalkthroughReviewStrategy,
} from './lib/walkthrough-authoring.ts';
