export {
  classifyGitLabCommit,
  classifyMergeRequestReviewStrategy,
  classifyReviewCommit,
  classifyReviewStrategy,
  orderCommitsTopologically,
  overrideMergeRequestReviewStrategy,
  reviewStructureFromStrategy,
  versionCompareReviewStructureKey,
  type ClassifiedCommit,
  type ClassifiedCommitRole,
  type GitLabMergeRequestCommitLike,
  type MergeRequestReviewStrategy,
  type ReviewStrategyCommitLike,
} from '@nkzw/codiff-core';
